[version]
path = "dbt/adapters/confluent/__version__.py"

[build.targets.wheel]
packages = ["dbt/adapters", "dbt/include"]
sources = ["./"]

[envs.default]
pre-install-commands = [
  "pip inspall -e ../dbt-adapters",
  "pip install -e ../dbt-tests-adapter"
]
dependencies = [
  "dbt-common @ git+https://github.com/dbt-labs/dbt-common.git",
  "dbt-core @ git+https://github.com/dbt-labs/dbt-core.git#subdirectory=core",
  "confluent-sql @ file://{root:parent}/confluent-sql/",
  "pytest~=7.0",
]
[envs.default.scripts]
unit-tests = "python -m pytest {args:tests/unit}"
integration-tests = "python -m pytest {args:tests/functional}"

[envs.build]
detached = true
dependencies = [
  "wheel",
  "twine",
  "check-wheel-contents",
]
