[executor]
type = "uv"
python = "3.11"

# Static code checks
[tasks.ruff-check]
help = "Run Ruff linter"
cmd = "ruff check dbt/ tests/"

[tasks.ruff-format-check]
help = "Check code formatting with Ruff (no changes applied)"
cmd = "ruff format --check dbt/ tests/"

[tasks.mypy]
help = "Run Mypy static type checks"
cmd = "mypy dbt/"

[tasks.lint]
help = "Run all static checks"
sequence = [
    "ruff-check",
    "ruff-format-check",
    "mypy",
]

# Test suite tasks
[tasks.unit]
help = "Run unit tests with coverage"
cmd = "pytest tests/unit --junitxml=test-results.xml --cov"

[tasks.integration]
help = "Run integration (functional) tests with coverage"
cmd = "pytest tests/functional --junitxml=test-results.xml --cov"

[tasks.test-all]
help = "Run full test suite with JUnit XML report and coverage"
cmd = "pytest --junitxml=test-results.xml --cov"

# Other
[tasks.cicd]
help = "Run static checks and unit tests"
sequence = [
    "lint",
    "unit",
]

[tasks.install-git-hooks]
help = "Install git hooks"
cmd = "pre-commit install --hook-type pre-push"
